# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ../../Polcovodetz/Core/BaseClasses/ICommandController.h \
    ../../Polcovodetz/Core/BaseClasses/IGroupController.h \
    ../../Polcovodetz/Core/BaseClasses/ILoader.h \
    ../../Polcovodetz/Core/BaseClasses/IObjectController.h \
    ../../Polcovodetz/Core/BaseClasses/ICommandDrivers.h \
    ../../Polcovodetz/Core/BaseClasses/IGroupDrivers.h \
    ../../Polcovodetz/Core/BaseClasses/IObjectDrivers.h \
    ./Implementations/Loader.h \
    ./Implementations/SimpleCommandController.h

#Source files
SOURCES += ./Implementations/Loader.cpp \
    ./Implementations/SimpleCommandController.cpp \
    ./main.cpp
