<?xml version="1.0" encoding="UTF-8"?>
<Intellect>

    <DynamicLibrary FileName="SimpleController.dll" ID="1"/>
    
    <Map FileName="SimpleMap.map"/>
    
    <CommandController LibraryID="1" Side="1" />
    <CommandController LibraryID="1" Side="2" />
    
    <GroupController LibraryID="1" Side="1" ID="1"/>
    <GroupController LibraryID="1" Side="2" ID="2"/>
    
    <ObjectController LibraryID="1" Side="2" GroupID="2" PObjectID="1"/>

</Intellect>
