# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./GUI/TopLevelControls/GUIControler.h \
    ./GUI/TopLevelControls/MainForm.h \
    ./GUI/SpecialControls/MapView.h \
    ./GUI/SpecialControls/PaintArea2D.h \
    ./Core/PolkApp.h \
    ./Core/BaseClasses/ILoader.h \
    ./Core/BaseClasses/ICommandDrivers.h \
    ./Core/BaseClasses/IGroupDrivers.h \
    ./Core/BaseClasses/IObjectDrivers.h \
    ./Core/BaseClasses/ICommandController.h \
    ./Core/BaseClasses/IGroupController.h \
    ./Core/BaseClasses/IObjectController.h \
    ./Core/Common/DualArray.h \
    ./Core/Common/Map.h \
    ./Core/PObjects/PObject.h \
    ./Core/PObjects/PObjectSharedImpl.h \
    ./Core/PObjects/UserObjects/Moving/SimpleTank.h \
    ./Core/MultiThreading/CommandThread.h \
    ./Core/MultiThreading/VisualThread.h

#Source files
SOURCES += ./GUI/TopLevelControls/GUIControler.cpp \
    ./GUI/TopLevelControls/MainForm.cpp \
    ./GUI/SpecialControls/MapView.cpp \
    ./GUI/SpecialControls/PaintArea2D.cpp \
    ./Core/PolkApp.cpp \
    ./Core/Common/Map.cpp \
    ./Core/PObjects/PObject.cpp \
    ./Core/PObjects/UserObjects/Moving/SimpleTank.cpp \
    ./Core/MultiThreading/CommandThread.cpp \
    ./Core/MultiThreading/VisualThread.cpp \
    ./main.cpp
