######################################################################
# Automatically generated by qmake (2.01a) ?? 20. ??? 23:16:01 2009
######################################################################

TEMPLATE = app
TARGET = Polcovodetz
DEPENDPATH += . \
              Core \
              Internationalization \
              Core\BaseClasses \
              Core\Common \
              Core\Drivers \
              Core\MultiThreading \
              Core\PObjects \
              GUI\CommonControls \
              GUI\SpecialControls \
              GUI\TopLevelControls \
              Core\PObjects\UserObjects\Moving
INCLUDEPATH += .

# Input
HEADERS += Core/PObjectFactory.h \
           Core/PolkApp.h \
           Core/ResourceManager.h \
           Core/BaseClasses/IAbstractController.h \
           Core/BaseClasses/ICommandController.h \
           Core/BaseClasses/ICommandDrivers.h \
           Core/BaseClasses/IGroupController.h \
           Core/BaseClasses/IGroupDrivers.h \
           Core/BaseClasses/ILoader.h \
           Core/BaseClasses/IObjectController.h \
           Core/BaseClasses/IObjectDrivers.h \
           Core/Common/DualArray.h \
           Core/Common/Map.h \
           Core/Drivers/SimpleCommandDrivers.h \
           Core/MultiThreading/CommandThread.h \
           Core/MultiThreading/VisualThread.h \
           Core/PObjects/PObject.h \
           Core/PObjects/PObjectSharedImpl.h \
           GUI/CommonControls/CommandControllerChooseForm.h \
           GUI/CommonControls/GroupControllerChooseForm.h \
           GUI/CommonControls/ObjectControllerChooseForm.h \
           GUI/CommonControls/PObjectChooseBox.h \
           GUI/SpecialControls/MapView.h \
           GUI/SpecialControls/PaintArea2D.h \
           GUI/TopLevelControls/CommandTreeForm.h \
           GUI/TopLevelControls/GUIControler.h \
           GUI/TopLevelControls/MainForm.h \
           Core/PObjects/UserObjects/Moving/SimpleTank.h \
           GUI/SpecialControls/Resources/CommandImage.xpm \
           GUI/SpecialControls/Resources/GroupImage.xpm \
           GUI/SpecialControls/Resources/ObjectImage.xpm \
           GUI/SpecialControls/Resources/Refresh.xpm \
           GUI/SpecialControls/Resources/Map/Empty.xpm \
           GUI/SpecialControls/Resources/Map/Brick.xpm \
           GUI/SpecialControls/Resources/Map/Grassland.xpm \
           GUI/SpecialControls/Resources/Map/Stone.xpm \
           GUI/SpecialControls/Resources/Map/Water.xpm \
           GUI/SpecialControls/Resources/Map/BlueStartPlace.xpm \
           GUI/SpecialControls/Resources/Map/RedStartPlace.xpm \
           Core/PObjects/Resources/BlueSimpleTank.xpm \
           Core/PObjects/Resources/RedSimpleTank.xpm
SOURCES += main.cpp \
           Core/PObjectFactory.cpp \
           Core/PolkApp.cpp \
           Core/ResourceManager.cpp \
           Core/Common/DualArray.cpp \
           Core/Common/Map.cpp \
           Core/Drivers/SimpleCommandDrivers.cpp \
           Core/MultiThreading/CommandThread.cpp \
           Core/MultiThreading/VisualThread.cpp \
           Core/PObjects/PObject.cpp \
           GUI/CommonControls/CommandControllerChooseForm.cpp \
           GUI/CommonControls/GroupControllerChooseForm.cpp \
           GUI/CommonControls/ObjectControllerChooseForm.cpp \
           GUI/CommonControls/PObjectChooseBox.cpp \
           GUI/SpecialControls/MapView.cpp \
           GUI/SpecialControls/PaintArea2D.cpp \
           GUI/TopLevelControls/CommandTreeForm.cpp \
           GUI/TopLevelControls/GUIControler.cpp \
           GUI/TopLevelControls/MainForm.cpp \
           Core/PObjects/UserObjects/Moving/SimpleTank.cpp
TRANSLATIONS += Internationalization/English.ts Internationalization/Russian.ts
